node {
    def dockerImage = 'maven:3.9.0'

    stage('Build') {
        checkout scm
        docker.image(dockerImage).inside("-v /root/.m2:/root/.m2") {
            sh 'mvn -B -DskipTests clean package'
        }
    }

    stage('Test') {
        checkout scm
        docker.image(dockerImage).inside {
            sh 'mvn test'
        }
        junit 'target/surefire-reports/*.xml'
    }

    stage('Deliver') {
        checkout scm
        sh './jenkins/scripts/deliver.sh'
    }
}
